[project]
name = "fracta"
version = "0.0.0"
description = "Python & Typescript based web-app for Viewing & Manipulating Timeseries Data."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "jack_of_some_trades" }]
license = { text = "TBD" }
requires-python = ">=3.12"
dependencies = [
    "alpaca-py>=0.39.1",
    "dotenv>=0.9.9",
    "fastapi>=0.115.0",
    "pandas>=2.2.2",
    "pandas-market-calendars>=4.6.0",
    "psyscale>=0.1.1",
    "pydantic>=2.11.3",
    "uvicorn[standard]>=0.34.0",
]

[tool.setuptools]
packages = ["fracta", "fracta.charting", "fracta.indicators", "fracta.broker_apis"]
include-package-data = true

[tool.setuptools.package-data]
fracta = ["frontend/*", "charting/*", "indicators/*", "broker_apis/*"]

[project.optional-dependencies]
dist = [
    "setuptools>=80.7.1",
    "twine>=6.1.0",
    "wheel>=0.45.1",
    "build>=1.2.2.post1",
]

[tool.black]
line-length = 120

[tool.pylint."MESSAGES CONTROL"]
max-line-length=120

[dependency-groups]
dev = [
    "pandas-stubs>=2.3.3.251219",
]

[project.entry-points."fracta.indicator_pkg"]
pkg_info = "fracta.indicators.__metadata__:PKG_INFO"
